// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFEp9Pz6KqQwJ8B1pLDt0S0QrOoBz-WWU',
    appId: '1:441075123976:web:2291e4d93bedd88e410ebd',
    messagingSenderId: '441075123976',
    projectId: 'early-barber',
    authDomain: 'early-barber.firebaseapp.com',
    storageBucket: 'early-barber.firebasestorage.app',
    measurementId: 'G-ZMP951SEQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YClgmuTR3qApKqFxch7h5LFPGM3WSEs',
    appId: '1:441075123976:android:c1a0e50171795c51410ebd',
    messagingSenderId: '441075123976',
    projectId: 'early-barber',
    storageBucket: 'early-barber.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFEp9Pz6KqQwJ8B1pLDt0S0QrOoBz-WWU',
    appId: '1:441075123976:web:62251460d6d216bb410ebd',
    messagingSenderId: '441075123976',
    projectId: 'early-barber',
    authDomain: 'early-barber.firebaseapp.com',
    storageBucket: 'early-barber.firebasestorage.app',
    measurementId: 'G-NKDGY91FQZ',
  );
}
